import { AccountEntity } from "../persistence/entities";

export let accountDataBase: AccountEntity[] = [
  {
    accountType: { id: "0", name: "asd0", state: true },
    balance: 1000,
    customer: {
      id: "0",
      documentType: { id: "0", name: "asd0", state: true },
      document: "string",
      fullName: "Daniel Basto 0",
      email: "daniel1@daniel0.com",
      phone: "562135465",
      password: "asdasdweqsdzxc",
      state: true,
    },
    id: "0",
    state: true,
  },
  {
    accountType: { id: "1", name: "asd1", state: true },
    balance: 1000,
    customer: {
      id: "1",
      documentType: { id: "1", name: "asd1", state: true },
      document: "string",
      fullName: "Daniel Basto 1",
      email: "daniel1@daniel1.com",
      phone: "562135465",
      password: "asdasdweqsdzxc",
      state: true,
    },
    id: "1",
    state: false,
  },
  {
    accountType: { id: "2", name: "asd2", state: true },
    balance: 0,
    customer: {
      id: "2",
      documentType: { id: "2", name: "asd2", state: true },
      document: "string",
      fullName: "Daniel Basto 2",
      email: "daniel1@daniel2.com",
      phone: "562135465",
      password: "asdasdweqsdzxc",
      state: true,
    },
    id: "2",
    state: true,
  },
  {
    accountType: { id: "3", name: "asd3", state: true },
    balance: 0,
    customer: {
      id: "3",
      documentType: { id: "3", name: "asd3", state: true },
      document: "string",
      fullName: "Daniel Basto 3",
      email: "daniel1@daniel3.com",
      phone: "562135465",
      password: "asdasdweqsdzxc",
      state: true,
    },
    id: "3",
    state: true,
  },
];
